# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(544, 441)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(50, 30))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cbModel = QtWidgets.QComboBox(Dialog)
        self.cbModel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cbModel.setObjectName("cbModel")
        self.horizontalLayout_2.addWidget(self.cbModel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lblClass = QtWidgets.QLabel(Dialog)
        self.lblClass.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lblClass.setAlignment(QtCore.Qt.AlignCenter)
        self.lblClass.setObjectName("lblClass")
        self.verticalLayout.addWidget(self.lblClass)
        self.lblImage = QtWidgets.QLabel(Dialog)
        self.lblImage.setText("")
        self.lblImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImage.setObjectName("lblImage")
        self.verticalLayout.addWidget(self.lblImage)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pbBrows = QtWidgets.QPushButton(Dialog)
        self.pbBrows.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbBrows.setObjectName("pbBrows")
        self.horizontalLayout.addWidget(self.pbBrows)
        spacerItem2 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.bpClassify = QtWidgets.QPushButton(Dialog)
        self.bpClassify.setMaximumSize(QtCore.QSize(16777215, 25))
        self.bpClassify.setObjectName("bpClassify")
        self.horizontalLayout.addWidget(self.bpClassify)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Model:"))
        self.lblClass.setText(_translate("Dialog", "Unknown"))
        self.pbBrows.setText(_translate("Dialog", "Brows file..."))
        self.bpClassify.setText(_translate("Dialog", "Predict"))
